### PR TITLE
Polish translation (ISSUE #122)

### PR DESCRIPTION
**Pull request by wilkoklak**
Please, add this to your list of translations in progress. I hope I'm doing it okay, since it's my first collaboration on github, tell me if I should do it in another way :)

### CODE REVIEW

**Comment by wilkoklak** [comment]
Oh, I've seen that there's translation folder. I'll create an issue now :)

**Comment by wilkoklak** [comment]
I've moved my file into translations folder, @jwasham

**Comment by jwasham** [comment]
When you're ready for me to pull, let me know.

**Comment by wilkoklak** [comment]
@jwasham I'm afraid I don't have time for translation now, so it might take a while, sorry...

**Comment by jwasham** [comment]
No rush, take your time.

**Comment by wilkoklak** [comment]
@jwasham 
How should I do it? Merging will only give you the file that I changed, right? I'm asking because my repo is a lot of commits behind. How can I update it without loosing my own file?

**Comment by jwasham** [comment]
I can merge this at any time. Correct, there is only one file changed:
https://github.com/jwasham/google-interview-university/pull/121/files

**Comment by wilkoklak** [comment]
Ok, you can merge this for now. It's not much but I will get to work and do more translations soon. Not this weekend, a lot of other work to do, but next week :)

**Comment by jwasham** [comment]
Thank you!

**Pull request merged**
