### PR TITLE
[WIP] Translation for Bahasa Indonesia

### PR DESCRIPTION
**Pull request by rvlewerissa**
This will be the translation for Bahasa Indonesia. Still working on it :) 
Will appreciate any form of help! 👍

Cheers!

### CODE REVIEW

**Comment by jwasham** [comment]
Let me know when you want me to pull.

**Comment by santosomichael** [comment]
@jwasham Sorry if I look like spamming, I'm confused where to start to fork. Do I have to wait for your merge into translation folder on the master?

**Comment by rvlewerissa** [comment]
@santosomichael try to use the same method I've described in the issue again, it should automatically push to this PR.

**Comment by rvlewerissa** [comment]
@fahminlb33 try not to merge branch ya, just rebase the branch it so it will look linear 👍

**Comment by fahminlb33** [comment]
Sorry, I'm using VSCode to push, I think VSCode automatically merge it. I'll use git bash from now (y)

**Comment by rvlewerissa** [comment]
@santosomichael yes, because your branch's commit is behind the remote branch, to avoid the normal merging (which logs a new commit saying that the branch is merged), you can just rebase it. So whenever you try to push to the remote repo, do this first:
`git origin indonesiaTranslation --rebase`

Then you can safely push it. You might want to check this:
https://www.atlassian.com/git/tutorials/merging-vs-rebasing/conceptual-overview

**Comment by santosomichael** [comment]
@rvlewerissa Thank's a lot for this great information

**Comment by rvlewerissa** [comment]
@jwasham Hi, this PR has gone quite long and up for quite some time.

What do you think on merging it first?

Thanks, man.

**Comment by jwasham** [comment]
Will do.

**Pull request merged**
