### PR TITLE
Adding more descriptive links.

### PR DESCRIPTION
**Pull request by Carmezim**
Improving readability and making a cleaner template.
If you agree with the changes I can follow finishing the file.

### CODE REVIEW

**Comment by jwasham** [comment]
This looks great! Thanks!
For the videos (Youtube, Coursera, etc), would you mind adding (video) to the descriptions?

**Comment by Carmezim** [comment]
Thank you for putting all this together and making it available! 
Sure. I had updated up to L540 though and lost the commit for some reason. I think you were just merging while I was finishing the editing so it did not get the commit =/.  I will redo afterwards and add the (video).

The file is huge so is it alright if I keep the updates in chunks?
I will try to have it finished tomorrow though.

**Comment by jwasham** [comment]
Ouch! Lost commits! 
Feel free to do so in chunks. 
This will really help the readability. This started as just a personal to-do list that got out of hand.

**Comment by Carmezim** [comment]
No worries, I recovered it also (phew). 
Nice, I will be finishing it at last by tomorrow and committing as I advance then ping you when complete.
I now removed to the next commit two coursera links, [this](https://github.com/jwasham/google-interview-university/pull/9/commits/6a3f07da79da7ea9d89579c803812da59b6190ce#diff-04c6e90faac2675aa89e2176d2eec7d8R265) and the one below at the compilers topic due to being deprecated.  They are still on the actual file so you can check it if you want.
This is amazing and thank you once again for building it and publicly sharing! 

And btw, I wish you all success on your endeavor!

**Comment by jwasham** [comment]
I've been wanting to remove the Coursera and Lynda.com (all courses) links because the links don't work when classes are not in session. If you can find related Youtube videos, please replace them with Youtube videos.

**Pull request merged**
