### PR TITLE
Next piece of translation Hindi

### PR DESCRIPTION
**Pull request by MrSourabh**
Additional translation Bottom up

### CODE REVIEW

**Comment by jwasham** [comment]
When you're ready for me to pull, let me know.

**Comment by MrSourabh** [comment]
@jwasham hi John, sorry didn't get time to work on next bit. Planning to complete it by next weekend.

**Comment by jwasham** [comment]
Don't worry about it. I just wanted to be sure I wasn't a blocker.

**Comment by aashil** [comment]
@MrSourabh @jwasham Hey, you guys mind me contributing to this?

**Comment by MrSourabh** [comment]
Not at all. Glad you can help

**Comment by MrSourabh** [comment]
@jwasham can you please merge this PR

**Comment by jwasham** [comment]
Thank you!

**Pull request merged**
