### PR TITLE
French translation draft

### PR DESCRIPTION
**Pull request by amoulkaf**

### CODE REVIEW

**Comment by jwasham** [comment]
Hi @amoulkaf  Did you want me to pull this now, or once it's done?

**Comment by amoulkaf** [comment]
Hi @jwasham I would like it to be pulled after a review I am currently working on. I will tell you when it's done.

**Comment by jwasham** [comment]
Please move your translation file to the translations directory. Thank you!

**Comment by amoulkaf** [comment]
Hi, can you pull this so the translation file can be visible  ?

**Pull request merged**
